# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    cpus-per-task: 2
    mem:  16G
    output: results/logs/slurm-%x.%A.%a.log

fastp_pe:
    cpus-per-task: 2
    mem:  16G
    cores: 2
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

bwa_mem:
    cpus-per-task: 8
    mem:  64G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

samtools_index:
    cpus-per-task: 4
    mem:  32G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

remove_duplicates:
    cpus-per-task: 3
    mem:  24G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

samtools_dedup_index:
    cpus-per-task: 4
    mem:  32G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

Get_Watson_Reads:
    cpus-per-task: 2
    mem:  16G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

samtools_index_Watson_Reads:
    cpus-per-task: 4
    mem:  32G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

Get_Crick_Reads:
    cpus-per-task: 2
    mem:  16G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

samtools_index_Crick_Reads:
    cpus-per-task: 4
    mem:  32G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

calculate_rfd:
    cpus-per-task: 2
    mem:  24G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

