# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    cpus-per-task: 2
    mem:  16G
    output: results/logs/slurm-%x.%A.%a.log

run_bwa_mem:
    cpus-per-task: 12
    mem:  96G
    cores: 12
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_pairs_with_pairtools_parse:
    cpus-per-task: 2
    mem:  16G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

sort_pairs_with_pairtools_sort:
    cpus-per-task: 8
    mem:  96G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

mark_duplicates_with_pairtools_dedup:
    cpus-per-task: 2
    mem:  16G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

filter_pairs:
    cpus-per-task: 2
    mem:  16G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

add_frag2Pairs:
    cpus-per-task: 2
    mem:  16G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

run_cooler:
    cpus-per-task: 12
    mem:  96G
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err
